/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an Owner
         * @description Creates an Owner and immediately starts a session. Email comparison is
         *     case-insensitive; the typed casing is preserved for display.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** @description Stored as a bcrypt hash. Never returned by any endpoint. */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Owner created; session cookie set */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["SessionCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                /** @description Email already registered (`EMAIL_TAKEN`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a session
         * @description Returns `401 UNAUTHENTICATED` for both a wrong password and an unknown
         *     email. Distinguishing them would turn this endpoint into an account
         *     enumeration oracle.
         *
         *     Rate limited to 5 attempts per minute per IP.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Session started */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["SessionCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Clears the cookie in the browser. It does NOT invalidate the JWT
         *     server-side — there is no revocation list. A copied token remains valid
         *     until it expires. Documented compromise; see 02-nfr.md.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cookie cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current Owner
         * @description The only way for the frontend to answer "am I logged in?", since the
         *     session cookie is httpOnly and unreadable from JavaScript.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current Owner */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List own Links
         * @description Newest first. Soft-deleted Links are never returned.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    /** @description Case-insensitive substring match on Short Code or Destination. */
                    search?: string;
                    status?: "ACTIVE" | "DISABLED" | "EXPIRED";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of Links */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LinkPage"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        /**
         * Create a Link
         * @description With no `alias`, a 7-character base62 Short Code is generated. With an
         *     `alias`, that exact string is claimed or the request fails — it never
         *     silently falls back to a generated code.
         *
         *     Rate limited: 10/minute per IP and 100/hour per Owner.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLinkRequest"];
                };
            };
            responses: {
                /** @description Link created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Link"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
                /**
                 * @description `ALIAS_TAKEN` — the Alias is already in the Code Namespace.
                 *     `RESERVED_ALIAS` — the Alias is a Reserved Word.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /**
                 * @description `INVALID_DESTINATION` — not an absolute http/https URL.
                 *     `DESTINATION_NOT_ALLOWED` — a Private Destination, or one of our own
                 *     hostnames.
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["RateLimited"];
                /**
                 * @description `INTERNAL` — includes the case where three Short Code generation
                 *     attempts all collided. Should be effectively impossible at a 0.003%
                 *     fill ratio; if it ever happens the collision-retry metric will show it.
                 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** One Link */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The Link */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Link"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a Link
         * @description Soft delete. The Link stops redirecting and leaves the Owner's list, but
         *     the row is retained and **the Short Code is never released**. Reusing a
         *     code would silently repoint a link that someone has already shared.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a Link
         * @description Only `destination`, `status` and `expiresAt` are mutable. The Short Code
         *     can never change: renaming would release the old string back into the
         *     Code Namespace for someone else to claim.
         *
         *     An absent field means "leave alone". An explicit `null` for `expiresAt`
         *     means "clear the expiry".
         *
         *     A destination change is recorded in the destination history and evicts
         *     the Link from the redirect cache.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateLinkRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Link"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
                /** @description `INVALID_DESTINATION` or `DESTINATION_NOT_ALLOWED` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/links/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Click statistics for a Link
         * @description Counts are approximate by design — analytics, not an audit log.
         *     Visible only to the Owner.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive. Defaults to 30 days ago. */
                    from?: string;
                    /** @description Inclusive. Defaults to today. */
                    to?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LinkStats"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Follow a Short Link
         * @description **Served on the SHORT host (`https://s.example.com/{code}`), not under
         *     `/api`.** It appears in this spec for completeness; the entire root
         *     namespace of the short host belongs to Short Codes.
         *
         *     Answers `302`, never `301`: a permanent redirect is cached by the browser
         *     forever, which would make Click counts meaningless and make a Destination
         *     change invisible to anyone who had already followed the link.
         *
         *     Unknown, Disabled, Expired and Deleted all return an **identical** `404`.
         *     A Visitor cannot tell which of the four applies.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the Destination */
                302: {
                    headers: {
                        Location?: string;
                        "Cache-Control"?: "private, no-cache";
                        "X-Robots-Tag"?: "noindex";
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown, Disabled, Expired or Deleted — indistinguishable by design. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457. Switch on `code`; `title` and `detail` may be reworded. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Machine-readable and part of the contract.
             * @enum {string}
             */
            code: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "NOT_FOUND" | "ALIAS_TAKEN" | "RESERVED_ALIAS" | "EMAIL_TAKEN" | "INVALID_DESTINATION" | "DESTINATION_NOT_ALLOWED" | "RATE_LIMITED" | "INTERNAL";
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        Owner: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        Link: {
            id: string;
            /** @description Case-sensitive. Immutable for the life of the Link. */
            code: string;
            /**
             * Format: uri
             * @description Fully formed by the server from configuration. The frontend must
             *     never build this by concatenating a base URL with `code`.
             */
            shortUrl: string;
            /** Format: uri */
            destination: string;
            /**
             * @description `EXPIRED` is derived from `expiresAt`, not stored. Only `ACTIVE` and
             *     `DISABLED` exist in the database.
             * @enum {string}
             */
            status: "ACTIVE" | "DISABLED" | "EXPIRED";
            isCustomAlias: boolean;
            /** Format: int64 */
            clickCount: number;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateLinkRequest: {
            /**
             * Format: uri
             * @description Absolute http/https only. Must not be a Private Destination.
             */
            destination: string;
            /**
             * @description Case-sensitive, globally unique across the whole Code Namespace —
             *     not scoped per Owner. Omit to have one generated.
             */
            alias?: string | null;
            /**
             * Format: date-time
             * @description Must be in the future.
             */
            expiresAt?: string | null;
        };
        /** @description Absent field = leave alone. Explicit `null` for `expiresAt` = clear it. */
        UpdateLinkRequest: {
            /** Format: uri */
            destination?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "DISABLED";
            /** Format: date-time */
            expiresAt?: string | null;
        };
        LinkPage: {
            content: components["schemas"]["Link"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        LinkStats: {
            linkId: string;
            /** Format: int64 */
            totalClicks: number;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            daily: {
                /** Format: date */
                date: string;
                /** Format: int64 */
                clicks: number;
            }[];
            /** @description `XX` means unknown — normal outside production. */
            byCountry?: {
                countryCode?: string;
                /** Format: int64 */
                clicks?: number;
            }[];
            byReferrer?: {
                /** @description `null` host means direct. */
                referrer?: string;
                /** Format: int64 */
                clicks?: number;
            }[];
            byDevice?: {
                /** @enum {string} */
                deviceType?: "DESKTOP" | "MOBILE" | "TABLET" | "BOT" | "UNKNOWN";
                /** Format: int64 */
                clicks?: number;
            }[];
        };
    };
    responses: {
        /** @description `UNAUTHENTICATED` — no valid session */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `NOT_FOUND` — the resource does not exist, **or belongs to another Owner**.
         *     Deliberately indistinguishable: a `403` would confirm it exists.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `VALIDATION_FAILED` — see the `errors` array for the fields */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `RATE_LIMITED` */
        RateLimited: {
            headers: {
                /** @description Seconds until the next attempt is permitted */
                "Retry-After"?: number;
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Sets the session cookie */
        SessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
